notifications:
  email: false
env:
  global:
    - TERM=dumb
language: java
jdk: openjdk8
service:
  - docker
addons:
  apt:
    packages:
      - bash
      - curl
      - docker-ce
install: true
before_install:
  - sudo pip install docker-compose httpie >/dev/null 2>&1
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
  - stop_any 80 8080 3000
script:
  - ./mvnw >/dev/null
  - ./mvnw -P docker docker-compose:up
  - http :8080/openapi
  - http :8080/api/v1/hello
  - http :8080/api/v1/hello/maven
  - ./mvnw -P docker docker-compose:down
  #
  - ./mvnw clean compile quarkus:build
  - java -jar ./target/*-runner.jar &
  - wait_for 8080
  - http :8080/openapi
  - http :8080/api/v1/hello
  - http :8080/api/v1/hello/maven
  - stop_any 80 8080
  #
  - ./gradlew >/dev/null
  - ./gradlew composeUp
  - http :8080/openapi
  - http :8080/api/v1/hello
  - http :8080/api/v1/hello/gradle
  - ./gradlew composeDown
  #
  - ./gradlew clean assemble quarkusBuild
  - java -jar ./build/*-runner.jar &
  - wait_for 8080
  - http :8080/openapi
  - http :8080/api/v1/hello
  - http :8080/api/v1/hello/gradle
  - stop_any 80 8080
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.docker
